#Basic Image
FROM ubuntu:20.04

#Args for compliance of inner and outer uid and gid

ARG cuid=1000
ARG cgid=1000
ARG cuidname=crusher
ARG cgidname=crusher

#Add group and user (like my HOST group and user)
RUN groupadd -g $cgid $cgidname &&  useradd -m -u $cuid -g $cgidname -G sudo -s /usr/bin/bash $cuidname

#Just a notes
LABEL maintainer="ponomarev@fobos-nt.ru"
LABEL version="1.0"
LABEL description="Persistence mode - CPP, C, anonymous namespaces etc"

#Set Timezone or get hang during the docker build...
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#Install common system packages
RUN apt update &&  apt-get install -y cmake  git make sudo wget build-essential python curl gcc lsb-release software-properties-common

#Install clang version 12
RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 12

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 100 && \
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 100 && \
update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-12 100 && \
update-alternatives --install /usr/bin/cc cc /usr/bin/clang-12 100 && \
update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-12 100 && \
update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-12 100 && \
update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-12 100 && \
update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-12 100 && \
update-alternatives --install /usr/bin/llvm-link llvm-link /usr/bin/llvm-link-12 100 && \
update-alternatives --install /usr/bin/llvm-objdump llvm-objdump /usr/bin/llvm-objdump-12 100

#Download and install Crusher
WORKDIR /home/$cuidname
RUN curl -o linux.zip -XGET "https://nextcloud.ispras.ru/index.php/s/xrtSXt8rMydRiFf/download?path=%2F&files=Linux" && \
unzip linux.zip -d ~ && \
cd ~/Linux && \
mkdir /opt/crusher && \
tar -xzf $(ls *crusher-linux-v*) --directory /opt/crusher 

#Clone AFL, version 3.14c
WORKDIR /home/$cuidname
RUN git clone --branch=3.14c --depth=1 https://github.com/AFLplusplus/AFLplusplus

#Build AFL++
WORKDIR /home/$cuidname/AFLplusplus
RUN make -j4

#Clone our test target - xml parsing library 'pugixml', version v1.11.14
WORKDIR /home/$cuidname
RUN git clone --branch=v1.11.4 --depth=1 https://github.com/zeux/pugixml 
WORKDIR /home/$cuidname/pugixml/src

USER root

#ENV cuidname=$cuidname
#ENV cgidname=$cgidname

#Install extra packages (if needed, for faster container repacking do it here)
RUN apt-get install -y vim mc

CMD /bin/bash
