#Basic Image
FROM ubuntu:20.04

#Args for compliance of inner and outer uid and gid

ARG cuid=1000
ARG cgid=1000
ARG cuidname=crusher
ARG cgidname=crusher

#Add group and user (like my HOST group and user)
RUN groupadd -g $cgid $cgidname &&  useradd -m -u $cuid -g $cgidname -G sudo -s /usr/bin/bash $cuidname

#Just a notes
LABEL maintainer="ponomarev@fobos-nt.ru"
LABEL version="1.0"
LABEL description="Persistence mode - CPP, C, anonymous namespaces etc"

#Set Timezone or get hang during the docker build...
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#Install common system packages
RUN apt update &&  apt-get install -y cmake  git make sudo wget build-essential python curl gcc lsb-release software-properties-common
RUN bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 100 && \
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 100 && \
update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-12 100 && \
update-alternatives --install /usr/bin/cc cc /usr/bin/clang-12 100 && \
update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-12 100 && \
update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-12 100 && \
update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-12 100 && \
update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-12 100 && \
update-alternatives --install /usr/bin/llvm-link llvm-link /usr/bin/llvm-link-12 100 && \
update-alternatives --install /usr/bin/llvm-objdump llvm-objdump /usr/bin/llvm-objdump-12 100

#Download and install Crusher
WORKDIR /home/$cuidname
RUN curl -XGET "https://raw.githubusercontent.com/DmitryJustDmitry/crusher/master/FAQ/fetch_crusher.sh" -o fetch_crusher.sh && chmod u+x fetch_crusher.sh && ./fetch_crusher.sh . 

#Clone AFL, version 3.14c
WORKDIR /home/$cuidname
RUN git clone --branch=3.14c --depth=1 https://github.com/AFLplusplus/AFLplusplus

#Build AFL++
WORKDIR /home/$cuidname/AFLplusplus
RUN make -j4

#Clone our test target - xml parsing library 'pugixml', version v1.11.14
WORKDIR /home/$cuidname
RUN git clone --branch=v1.11.4 --depth=1 https://github.com/zeux/pugixml

USER root

#ENV cuidname=$cuidname
#ENV cgidname=$cgidname

CMD /bin/bash
