# Base image
FROM ubuntu:jammy

# Install deps
RUN apt update -y \
    && apt install -y libglib2.0-0 openjdk-17-jdk git maven nano gnupg2 wget sudo \
    && rm -rf /var/lib/apt/lists/*

# Setup env
ARG USER_NAME
ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID $USER_NAME

RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID $USER_NAME

ENV WORK_DIR /home/$USER_NAME
WORKDIR $WORK_DIR

# Install hasp-service (for license)
RUN echo 'deb https://repo.ispras.ru/apt /' | tee /etc/apt/sources.list.d/ispras.list \
    && wget -q -O - https://repo.ispras.ru/apt/key.asc | apt-key add - \
    && apt update -y \
    && apt install -y aksusbd

# Setup license
RUN mkdir -p /etc/hasplm
COPY license/hasplm.ini /etc/hasplm/hasplm.ini
USER $USER_NAME
COPY license $WORK_DIR/license
# check
USER root
RUN $WORK_DIR/license/license.sh && $WORK_DIR/license/test-protected

# Keycloak & fuzz config
COPY keycloak-26.0.7 $WORK_DIR/keycloak-26.0.7
COPY config.json $WORK_DIR/config.json
