#Basic Image
FROM ubuntu:20.04

#Args for compliance of inner and outer uid and gid

ARG cuid=1000
ARG cgid=1000
ARG cuidname=crusher
ARG cgidname=crusher

#Just a notes
LABEL maintainer="ponomarev@fobos-nt.ru"
LABEL version="1.0"
LABEL description="Boilerplate for crusher work in stat inst mode"

#Install system packages
RUN apt update && apt install -y gcc clang llvm make sudo git wget

#Add group and user (like my HOST group and user)
RUN groupadd -g $cgid $cgidname &&  useradd -m -u $cuid -g $cgidname -G sudo -s /usr/bin/bash $cuidname

#Unpack Crusher
ADD crusher.tar.gz /home/$cuidname

#Compile afl++ compilers
WORKDIR /home/$cuidname
RUN wget https://github.com/AFLplusplus/AFLplusplus/archive/3.0c.tar.gz \
    && tar xvf 3.0c.tar.gz
WORKDIR /home/$cuidname/AFLplusplus-3.0c
RUN make -j10

#Getting inputs from HOST
WORKDIR /home/$cuidname
COPY in in/

################### Add your target here
#Set Timezone or get hang during the docker build...
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#Install Target for fuzzing
RUN apt install -y libreadline-dev zlib1g-dev bison flex libfl-dev
USER $cuidname
RUN git clone --single-branch --branch REL_12_STABLE --depth 1 https://github.com/postgres/postgres
WORKDIR /home/$cuidname/postgres

#Configuring and compiling the Target for fuzzing
RUN CC=/home/$cuidname/AFLplusplus-3.0c/afl-clang-fast CXX=/home/$cuidname/AFLplusplus-3.0c/afl-clang-fast++ AFL_USE_UBSAN=1 AFL_LLVM_LAF_ALL=1 ./configure --prefix /home/$cuidname/pgbuild
RUN make -j10 && make install
WORKDIR /home/$cuidname/

RUN /home/$cuidname/pgbuild/bin/initdb -D /home/$cuidname/data

###################

#Start fuzzer in a container (change ownership for output folder)
USER root
ENV cuidname=$cuidname
ENV cgidname=$cgidname
CMD echo core >/proc/sys/kernel/core_pattern \
    && chown -R $cuidname:$cgidname /home/$cuidname/out \
    && sudo -u $cuidname ./crusher/bin_x86-64/fuzz_manager --start 1 --eat-cores 0 --dse-cores 0 --dse-threads 0 -i in/ -o out/ -F -I StaticForkSrv --bitmap-size 150000 -T stdin -t 3000 -m 10000 --session $FUZZ_INSTANCE -- /home/$cuidname/pgbuild/bin/postgres --single -D /home/$cuidname/data postgres
